services:
  student-tracker:
    image: codebyamrit/student-tracker:latest
    container_name: student-tracker
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.edu.rule=Host(`edu.amritsharma.dev`) || Host(`school.cctvcameralive.in`)"
      - "traefik.http.routers.edu.entrypoints=websecure"
      - "traefik.http.routers.edu.tls.certresolver=letsencrypt"
      - "traefik.http.services.edu.loadbalancer.server.port=5000"

  # student-portal:
  #   build:
  #     context: ./student-portal
  #     dockerfile: Dockerfile

  #   restart: always

  #   networks:
  #     - proxy

  #   expose:
  #     - "80"

  #   environment:
  #     - VITE_API_URL=https://edu.amritsharma.dev/api/student

  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.student-portal.rule=Host(`students.amritsharma.dev`)"
  #     - "traefik.http.routers.student-portal.entrypoints=websecure"
  #     - "traefik.http.routers.student-portal.tls.certresolver=letsencrypt"
  #     - "traefik.http.services.student-portal.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
